---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
  - name: s3cli-src
run:
  path: s3cli-src/ci/tasks/teardown-infrastructure.sh
params:
  access_key_id:
  secret_access_key:
  region_name:
  stack_name:
