---
groups:
  - name: s3cli
    jobs:
      - unit
      - aws-s3-us-integration
      - aws-s3-china-integration
      - aws-s3-frankfurt-integration
      - s3-compatible-integration
      - promote

jobs:
  - name: unit
    serial: true
    plan:
      - aggregate:
          - {trigger: true, get: s3cli-src, resource: s3cli-in}

      - task: test
        file: s3cli-src/ci/tasks/run-unit.yml

  - name: aws-s3-us-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli-src, passed: [unit], resource: s3cli-in}

      - task: setup
        file: s3cli-src/ci/tasks/setup-aws-infrastructure.yml
        config: &aws-us-infrastructure-config
          params:
            access_key_id:     {{access_key_id__aws_us}}
            secret_access_key: {{secret_access_key__aws_us}}
            region_name:       {{region_name__aws_us}}
            stack_name:        {{stack_name__aws_us}}
            region_optional:   true
            ec2_ami:           {{ec2_ami__aws_us}}
            public_key_name:   {{public_key_name__aws_us}}
            alt_host:          s3-external-1.amazonaws.com
            valid_host:        s3-external-1.amazonaws.com

      - task: test
        file: s3cli-src/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:     {{access_key_id__aws_us}}
            secret_access_key: {{secret_access_key__aws_us}}
            region_name:       {{region_name__aws_us}}
            private_key_data:  {{private_key_data__aws_us}}
        ensure:
          task: teardown
          file: s3cli-src/ci/tasks/teardown-infrastructure.yml
          config: *aws-us-infrastructure-config

  - name: aws-s3-china-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli-src, passed: [unit], resource: s3cli-in}

      - task: setup
        file: s3cli-src/ci/tasks/setup-aws-infrastructure.yml
        config: &aws-china-infrastructure-config
          params:
            access_key_id:     {{access_key_id__aws_china}}
            secret_access_key: {{secret_access_key__aws_china}}
            region_name:       {{region_name__aws_china}}
            stack_name:        {{stack_name__aws_china}}
            region_optional:   false
            ec2_ami:           {{ec2_ami__aws_china}}
            public_key_name:   {{public_key_name__aws_china}}
            invalid_host:      s3-external-1.amazonaws.com
            valid_host:        s3.cn-north-1.amazonaws.com.cn

      - task: test
        file: s3cli-src/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:     {{access_key_id__aws_china}}
            secret_access_key: {{secret_access_key__aws_china}}
            region_name:       {{region_name__aws_china}}
            private_key_data:  {{private_key_data__aws_china}}
        ensure:
          task: teardown
          file: s3cli-src/ci/tasks/teardown-infrastructure.yml
          config: *aws-china-infrastructure-config

  - name: aws-s3-frankfurt-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli-src, passed: [unit], resource: s3cli-in}

      - task: setup
        file: s3cli-src/ci/tasks/setup-aws-infrastructure.yml
        config: &aws-frankfurt-infrastructure-config
          params:
            access_key_id:     {{access_key_id__aws_frankfurt}}
            secret_access_key: {{secret_access_key__aws_frankfurt}}
            region_name:       {{region_name__aws_frankfurt}}
            stack_name:        {{stack_name__aws_frankfurt}}
            region_optional:   false
            ec2_ami:           {{ec2_ami__aws_frankfurt}}
            public_key_name:   {{public_key_name__aws_frankfurt}}

      - task: test
        file: s3cli-src/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:     {{access_key_id__aws_frankfurt}}
            secret_access_key: {{secret_access_key__aws_frankfurt}}
            region_name:       {{region_name__aws_frankfurt}}
            private_key_data:  {{private_key_data__aws_frankfurt}}
        ensure:
          task: teardown
          file: s3cli-src/ci/tasks/teardown-infrastructure.yml
          config: *aws-frankfurt-infrastructure-config

  - name: s3-compatible-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli-src, passed: [unit], resource: s3cli-in}

      - task: setup
        file: s3cli-src/ci/tasks/setup-s3-compatible-configurations.yml
        config:
          params:
            access_key_id:     {{access_key_id__s3_compat}}
            secret_access_key: {{secret_access_key__s3_compat}}
            bucket_name:       {{bucket_name__s3_compat}}
            s3_endpoint_host:  {{host__s3_compat}}
            s3_endpoint_port:  {{port__s3_compat}}

      - task: test
        file: s3cli-src/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:     {{access_key_id__s3_compat}}
            secret_access_key: {{secret_access_key__s3_compat}}

  - name: promote
    plan:
      - aggregate:
          - {trigger: true, get: s3cli-src, passed: [unit, aws-s3-us-integration, aws-s3-china-integration, aws-s3-frankfurt-integration, s3-compatible-integration], resource: s3cli-in}
          - {trigger: false, get: version-semver, params: {bump: patch} }

      - {put: version-semver, params: {file: version-semver/number}}

      - task: build-linux
        file: s3cli-src/ci/tasks/build.yml

      - put: release-bucket-linux
        params: {file: out/s3cli-*-linux-amd64}

      - put: s3cli-src
        resource: s3cli-out
        params: {repository: s3cli-src, tag: version-semver/number, tag_prefix: v}

resources:
  - name: s3cli-in
    type: git
    source:
      uri: git@github.com:pivotal-golang/s3cli.git
      branch: develop
      private_key: {{github_deployment_key__s3cli}}

  - name: s3cli-out
    type: git
    source:
      uri: git@github.com:pivotal-golang/s3cli.git
      branch: master
      private_key: {{github_deployment_key__s3cli}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      bucket: {{s3cli_release_bucket}}
      access_key_id: {{s3cli_release_bucket_access_key}}
      secret_access_key: {{s3cli_release_bucket_secret_key}}

  - name: release-bucket-linux
    type: s3
    source:
      regexp: s3-(.*)-linux-amd64
      bucket: {{s3cli_release_bucket}}
      access_key_id: {{s3cli_release_bucket_access_key}}
      secret_access_key: {{s3cli_release_bucket_secret_key}}
