---
groups:
  - name: s3cli
    jobs:
      - trigger-build
      - aws-s3-integration
      - s3-compatible-integration
      - promote-candidate

jobs:
  - name: trigger-build
    plan:
      - {trigger: true, get: s3cli, resource: s3cli-in}

  - name: aws-s3-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli, passed: [trigger-build], resource: s3cli-in}

      - task: test
        file: s3cli/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:            {{access_key_id__aws}}
            secret_access_key:        {{secret_access_key__aws}}
            bucket_name:              {{bucket_name__aws}}
            region_name:              {{region_name__aws}}
            signature_version:        {{signature_version__aws}}
            host:                     {{host__aws}}
            port:                     {{port__aws}}

  - name: s3-compatible-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli, passed: [trigger-build], resource: s3cli-in}

      - task: test
        file: s3cli/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:            {{access_key_id__s3_compat}}
            secret_access_key:        {{secret_access_key__s3_compat}}
            bucket_name:              {{bucket_name__s3_compat}}
            region_name:              {{region_name__s3_compat}}
            signature_version:        {{signature_version__s3_compat}}
            host:                     {{host__s3_compat}}
            port:                     {{port__s3_compat}}

  - name: promote-to-master
    plan:
      - aggregate:
        - {trigger: false, get: s3cli, passed: [aws-s3-integration, s3-compatible-integration], resource: s3cli-in}

      - put: s3cli-out
        resource: s3cli-out
        params: {repository: s3cli}

resources:
  - name: s3cli-in
    type: git
    source:
      uri: git@github.com:pivotal-golang/s3cli.git
      branch: develop
      private_key: {{github_deployment_key__s3cli}}

  - name: s3cli-out
    type: git
    source:
      uri: git@github.com:pivotal-golang/s3cli.git
      branch: master
      private_key: {{github_deployment_key__s3cli}}

