---
groups:
  - name: s3cli
    jobs:
      - unit
      - aws-s3-us-integration
      - aws-s3-china-integration
      - aws-s3-frankfurt-integration
      - s3-compatible-integration
      - promote

  - name: versioning
    jobs:
      - bump-minor
      - bump-major
      - promote

jobs:
  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: {bump: minor}
      - {put: version-semver, params: {file: version-semver/number}}

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: {bump: major}
      - {put: version-semver, params: {file: version-semver/number}}

  - name: unit
    serial: true
    plan:
      - aggregate:
          - {trigger: true, get: s3cli, resource: s3cli-in}

      - task: test
        file: s3cli/ci/tasks/run-unit.yml

  - name: aws-s3-us-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli, passed: [unit], resource: s3cli-in}
      - task: test
        file: s3cli/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:            {{access_key_id__aws_us}}
            secret_access_key:        {{secret_access_key__aws_us}}
            bucket_name:              {{bucket_name__aws_us}}
            region_name:              {{region_name__aws_us}}
            host:                     {{host__aws_us}}
            port:                     {{port__aws_us}}

  - name: aws-s3-china-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli, passed: [unit], resource: s3cli-in}
      - task: test
        file: s3cli/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:            {{access_key_id__aws_china}}
            secret_access_key:        {{secret_access_key__aws_china}}
            bucket_name:              {{bucket_name__aws_china}}
            region_name:              {{region_name__aws_china}}
            host:                     {{host__aws_china}}
            port:                     {{port__aws_china}}

  - name: aws-s3-frankfurt-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli, passed: [unit], resource: s3cli-in}
      - task: test
        file: s3cli/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:            {{access_key_id__aws_frankfurt}}
            secret_access_key:        {{secret_access_key__aws_frankfurt}}
            bucket_name:              {{bucket_name__aws_frankfurt}}
            region_name:              {{region_name__aws_frankfurt}}
            host:                     {{host__aws_frankfurt}}
            port:                     {{port__aws_frankfurt}}


  - name: s3-compatible-integration
    serial: true
    plan:
      - {trigger: true, get: s3cli, passed: [unit], resource: s3cli-in}
      - task: test
        file: s3cli/ci/tasks/run-integration.yml
        config:
          params:
            access_key_id:            {{access_key_id__s3_compat}}
            secret_access_key:        {{secret_access_key__s3_compat}}
            bucket_name:              {{bucket_name__s3_compat}}
            region_name:              {{region_name__s3_compat}}
            host:                     {{host__s3_compat}}
            port:                     {{port__s3_compat}}

  - name: promote
    plan:
      - aggregate:
          - {trigger: true, get: s3cli, passed: [unit, aws-s3-us-integration, aws-s3-china-integration, aws-s3-frankfurt-integration, s3-compatible-integration], resource: s3cli-in}
          - get: version-semver
            params: {bump: patch}

      - {put: version-semver, params: {file: version-semver/number}}

      - task: build-linux
        file: s3cli/ci/tasks/build.yml

      - {put: release-bucket-linux, params: {from: build-linux/s3cli/out/s3}}

      - put: s3cli-out
        resource: s3cli-out
        params: {repository: s3cli}

resources:
  - name: s3cli-in
    type: git
    source:
      uri: git@github.com:pivotal-golang/s3cli.git
      branch: develop
      private_key: {{github_deployment_key__s3cli}}

  - name: s3cli-out
    type: git
    source:
      uri: git@github.com:pivotal-golang/s3cli.git
      branch: master
      private_key: {{github_deployment_key__s3cli}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      bucket: {{s3cli_release_bucket}}
      access_key_id: {{s3cli_release_bucket_access_key}}
      secret_access_key: {{s3cli_release_bucket_secret_key}}

  - name: release-bucket-linux
    type: s3
    source:
      regexp: s3-(.*)-linux-amd64
      bucket: {{s3cli_release_bucket}}
      access_key_id: {{s3cli_release_bucket_access_key}}
      secret_access_key: {{s3cli_release_bucket_secret_key}}
